### ISSUE TITLE
Add annualised growth rates function

### ISSUE THREAD

**Issue by pollytatouin** [christophsax/tsbox#107]
It would be nice to have a version of ts_pc() that annualises the growth rates. It would need to take into account the frequency of the series.

**Comment by pollytatouin** [comment]
Hi Christoph,

Perhaps annpc() ? 

I think the true calculation is more appropriate. I personally am using your awesome package at work and precision is important :)

Le 19 oct. 2018 à 12:27, Christoph Sax <notifications@github.com> a écrit :

Agreed, this sounds useful.

ts_pca() sounds a bit like principal component, do you know a better name?

Should it do the correct math, e.g. for quarterly data, (1 + pc)^4 - 1 or just pc * 4?

**Comment by christophsax** [comment]
Implemented in latest dev. 

@pollytatouin, does it work as expected?

``` r
tsbox::ts_pca(fdeaths)
#>               Jan          Feb          Mar          Apr          May
#> 1974           NA   -96.001168   794.201619   -90.942718   -95.584478
#> 1975  1303.609692   -69.403132    67.425573   -86.585297   -98.535175
#> 1976    -6.051072 11645.820662   -94.501194   -99.808026   -87.619143
#> 1977   325.565964   -95.940804     5.592996   -30.758043   -94.872414
#> 1978  1322.684724   129.314523   -82.693012   -97.266608   -30.016006
#> 1979   876.518767   -41.612753   -60.191387   -87.335031   -94.846317
#>               Jun          Jul          Aug          Sep          Oct
#> 1974   -95.099207   169.743303   -74.913069   -16.857903 13282.715194
#> 1975   -53.667391   -37.813542   -22.841915   -88.914307  1885.649896
#> 1976   -52.652047   -73.498976   -79.111217   156.951593  1307.024107
#> 1977   -94.859703    76.469257   -86.421585   257.750832    -6.028280
#> 1978   -87.390210   -33.670162   -87.675321   122.858259   254.070616
#> 1979   -72.688048   -49.884419   -54.896500    54.539707    71.155657
#>               Nov          Dec
#> 1974    -7.942697   447.717591
#> 1975   854.337820  8680.480518
#> 1976  1064.103462  5533.892947
#> 1977   119.065057 19477.006370
#> 1978   -13.094814 27554.775088
#> 1979   666.029813   618.778659
```

<sup>Created on 2019-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by pollytatouin** [comment]
Hi Christopher!

Sorry I let you down with this; I was planning on sending a pull request but it slipped my mind. Either way your implementation seems more robust than what I would have done.

The function works like a charm! And the new updates are really cool.

A big thank you, as always.
