### ISSUE TITLE
ts_seas does not accept additional arguments

### ISSUE THREAD

**Issue by CarolineSchmidt** [christophsax/tsbox#109]

**Comment by christophsax** [comment]
The function definition should be changed to 

```r
ts_seas <- ts_(function(x, ...) seasonal::final(seasonal::seas(x, ...)), vectorize = TRUE)
```

Now, this will work as expected:
```r
ts_seas(AirPassengers, x11 = "")
```

This should be a general principle: `ts_` derivatives of existing functions should pass additional arguments to their core functions.

As a workaround, just add the function definition from above in your script.

**Comment by christophsax** [comment]
However, vectorized use is still not working, due to #103
