### ISSUE TITLE
ts_seas: how to remove outliers?

### ISSUE THREAD

**Issue by vincentpochon** [christophsax/tsbox#115]
ts_seas() does not work on the following series:

`structure(list(country_name = c("Euroraum", "Euroraum", "Euroraum", 
"Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", 
"Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", 
"Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", 
"Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", 
"Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", 
"Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", 
"Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", 
"Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", 
"Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", 
"Euroraum", "Euroraum"), time = structure(c(16071, 16102, 16130, 
16161, 16191, 16222, 16252, 16283, 16314, 16344, 16375, 16405, 
16436, 16467, 16495, 16526, 16556, 16587, 16617, 16648, 16679, 
16709, 16740, 16770, 16801, 16832, 16861, 16892, 16922, 16953, 
16983, 17014, 17045, 17075, 17106, 17136, 17167, 17198, 17226, 
17257, 17287, 17318, 17348, 17379, 17410, 17440, 17471, 17501, 
17532, 17563, 17591, 17622, 17652, 17683, 17713, 17744, 17775, 
17805, 17836), class = "Date"), value = c(10230.996772, 10458.564099, 
10697.461212, 10681.865819, 10421.94534, 11101.98504, 11024.068647, 
9362.91241299999, 10736.902521, 11683.43659, 9864.812115, 10109.928069, 
8924.195664, 9672.823438, 10307.959104, 9677.943167, 8578.22747099999, 
10188.442975, 10222.471691, 7734.806035, 9649.618903, 10607.952575, 
10797.199278, 9565.838049, 8519.209095, 9495.206666, 10800.226408, 
10968.173227, 9479.88481799999, 10198.996123, 10354.705464, 8970.143293, 
10135.977975, 10683.417994, 10663.862909, 9699.297672, 9233.629469, 
9635.51675799999, 11285.976614, 9850.65289799999, 11423.766039, 
11176.820438, 10668.021167, 9932.23759199999, 10373.228271, 11681.948402, 
12044.434057, 9822.864258, 11403.279478, 10676.018516, 12247.013261, 
11373.194686, 11538.400673, 12094.583483, 11502.017862, 10079.407487, 
10336.956863, 12189.918184, 11647.015441)), row.names = c(NA, 
-59L), class = c("tbl_df", "tbl", "data.frame"), .Names = c("country_name", 
"time", "value"))`

I get the following error message:
`Error: X-13 run failed

Errors:
- Regression matrix singular because of AO2016.Feb.  Check regression model or change automatic
  outlier options i.e. method to addone or types to identify AO only.

Notes:
- Unable to test AO2016.Feb due to regression matrix singularity.`

removing the outlier in the series does the job, but ts_seas(outlier = NULL) does not work unfortunately.

Is there an efficient workaround?

Thanks

**Comment by christophsax** [comment]
In part an X-13 problem, in part connected to #109 

With latest dev version, this works:

``` r
library(tsbox)

x <- structure(list(country_name = c("Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum", "Euroraum"), time = structure(c(16071, 16102, 16130, 16161, 16191, 16222, 16252, 16283, 16314, 16344, 16375, 16405, 16436, 16467, 16495, 16526, 16556, 16587, 16617, 16648, 16679, 16709, 16740, 16770, 16801, 16832, 16861, 16892, 16922, 16953, 16983, 17014, 17045, 17075, 17106, 17136, 17167, 17198, 17226, 17257, 17287, 17318, 17348, 17379, 17410, 17440, 17471, 17501, 17532, 17563, 17591, 17622, 17652, 17683, 17713, 17744, 17775, 17805, 17836), class = "Date"), value = c(10230.996772, 10458.564099, 10697.461212, 10681.865819, 10421.94534, 11101.98504, 11024.068647, 9362.91241299999, 10736.902521, 11683.43659, 9864.812115, 10109.928069, 8924.195664, 9672.823438, 10307.959104, 9677.943167, 8578.22747099999, 10188.442975, 10222.471691, 7734.806035, 9649.618903, 10607.952575, 10797.199278, 9565.838049, 8519.209095, 9495.206666, 10800.226408, 10968.173227, 9479.88481799999, 10198.996123, 10354.705464, 8970.143293, 10135.977975, 10683.417994, 10663.862909, 9699.297672, 9233.629469, 9635.51675799999, 11285.976614, 9850.65289799999, 11423.766039, 11176.820438, 10668.021167, 9932.23759199999, 10373.228271, 11681.948402, 12044.434057, 9822.864258, 11403.279478, 10676.018516, 12247.013261, 11373.194686, 11538.400673, 12094.583483, 11502.017862, 10079.407487, 10336.956863, 12189.918184, 11647.015441)), row.names = c(NA, -59L), class = c("tbl_df", "tbl", "data.frame"), .Names = c("country_name", "time", "value"))

ts_seas(x, outlier = NULL)
#> Loading required namespace: tibble
#> # A tibble: 59 x 2
#>    time        value
#>    <date>      <dbl>
#>  1 2014-01-01 10699.
#>  2 2014-02-01 10674.
#>  3 2014-03-01 10563.
#>  4 2014-04-01 10503.
#>  5 2014-05-01 10526.
#>  6 2014-06-01 10656.
#>  7 2014-07-01 10653.
#>  8 2014-08-01 10796.
#>  9 2014-09-01 10585.
#> 10 2014-10-01 10355.
#> # … with 49 more rows
```

<sup>Created on 2019-03-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
