### ISSUE TITLE
ts_date()

### ISSUE THREAD

**Issue by srlanalytics** [christophsax/tsbox#135]
Could I put in a request for a new function? I often want to pull a date vector from a `ts_boxable()` object. It would be super slick to have a simple function ts_date() that does it for me regardless of the data format. Just a thought....

**Comment by christophsax** [comment]
Thanks. But why not just:

``` r
library(tsbox)
x <- AirPassengers
head(ts_df(x)$time)
#> [1] "1949-01-01" "1949-02-01" "1949-03-01" "1949-04-01" "1949-05-01"
#> [6] "1949-06-01"
```

If you want to be certain that the column is always called `time`, use the new `ts_default` function:

``` r
head(ts_df(ts_default(x))$time)
#> [1] "1949-01-01" "1949-02-01" "1949-03-01" "1949-04-01" "1949-05-01"
#> [6] "1949-06-01"
```

<sup>Created on 2019-03-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by christophsax** [comment]
@srlanalytics are you happy with my answer, or still longing for `ts_date()`?

**Comment by srlanalytics** [comment]
Sorry @christophsax... thought I'd already responded! Your solution works fine --- probably should have been able to figure that one out on my own! A `ts_date()` function might look a little prettier, but I guess that would be the only advantage.
