### ISSUE TITLE
ts_frequency, convert to higher frequency

### ISSUE THREAD

**Issue by christophsax** [christophsax/tsbox#142]

**Comment by JohannesTimm** [comment]
It would be nice if ts_frequency could convert to (non integer) sampling like weeks or days.

**Comment by christophsax** [comment]
Tempdisagg can now convert low frequency to high frequency data:

https://cran.r-project.org/web/packages/tempdisagg/vignettes/hf-disagg.html

But this is probably not fast or flexible enough to use it in `ts_frequency`. Since tempdisagg now accepts tsboxable objects, a link could be added to `ts_frequency`

Conversion to addition lower frequencies (e.g. days, hours etc. to weeks) shouldn't be too hard to do.

**Comment by christophsax** [comment]
Aggregation to lower frequencies is now a separate issue #183.

As for to higher frequencies, a link should be added.
