### ISSUE TITLE
Adding support of "tis" class

### ISSUE THREAD

**Issue by pollytatouin** [christophsax/tsbox#150]
I just noticed that there exists the "tis" package which offers another times series class: "tis".
https://cran.r-project.org/web/packages/tis/tis.pdf

It's far from a pressing need I believe, but perhaps in the future it could be nice to support this class for better universality.

**Comment by christophsax** [comment]
Sounds reasonable. Will have a look at it.

**Comment by christophsax** [comment]
Works now:

``` r
library(tsbox)
ts_plot(ts_tis(ts_c(mdeaths, AirPassengers)), austres)
#> Loading required namespace: tis
```

![](https://i.imgur.com/lWUtbei.png)

<sup>Created on 2019-06-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
