### ISSUE TITLE
Choose a different prefix for converter functions?

### ISSUE THREAD

**Issue by krlmlr** [christophsax/tsbox#163]
`tsc_ts()` and `tsc_tsibble()` instead of `ts_ts()`, ...?

Motivation: Distinguish converter functions from functions that alter the data.

`ts_()` is fine as a function name.

**Comment by christophsax** [comment]
The prefix looks good and quite consistent to me:

https://www.cynkra.com/slides/190712-tsbox/slides.html#39

All `ts_<whatever>` functions can be applied to any time series, so the difference between `ts_<class>` and `ts_<function>` is not so big.
