### ISSUE TITLE
Add piping/magrittr/dplyr support for ts_lag

### ISSUE THREAD

**Issue by osnofas** [christophsax/tsbox#176]
Hi! First of all, thank you for all of your hard work and contributions. This is a badly needed addition to the R toolbox.

This issue is an enhancement request. `ts_lag` doesn't appear to support piping, or at least fails in a very common scenario I copy below. (The data is imported from an Excel file using `read_excel`.) This makes some workflows very cumbersome, requiring the programmer to create another data.frame and merge it.

Thanks!!

```
> library(tidyverse)
> library(tsbox)
> test_data <- structure(list(date = structure(c(11750, 11751, 11752, 11753, 11754, 11757, 11758, 11759, 11760, 11761), class = "Date"), value = c(2.0083, 1.9917, 2.0508, 2.1375, 2.2033, 2.2525, 2.365, 2.3317, 2.365, 2.3408)), class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, -10L))
> ts_boxable(test_data)
[1] TRUE
> ts_lag(test_data, by = "1 day")
[time]: 'date' 
# A tibble: 10 x 2
   date       value
   <date>     <dbl>
 1 2002-03-05  2.01
 2 2002-03-06  1.99
 3 2002-03-07  2.05
 4 2002-03-08  2.14
 5 2002-03-09  2.20
 6 2002-03-12  2.25
 7 2002-03-13  2.37
 8 2002-03-14  2.33
 9 2002-03-15  2.37
10 2002-03-16  2.34
> test_data %>% mutate(lagged = ts_lag(by = "1 day"))
Error in ts_boxable(x) : argument "x" is missing, with no default
> test_data %>% mutate(lagged = ts_lag(., by = "1 day"))
[time]: 'date' 
Error: Column `lagged` is of unsupported class data.frame
> test_data %>% mutate(lagged = ts_lag(value, by = "1 day"))
Error in ts_lag(value, by = "1 day") : ts_boxable(x) is not TRUE
```

**Comment by christophsax** [comment]
Sorry for the late answer.

I thing that is expected: `ts_lag()` can be used on a tibble, and will return a tibble. But you want to use functions that work on vectors within `mutate()`.

Of course, you can still use `ts_lag()` with a pipe, just don't use `mutate()`:

```r
test_data %>% ts_lag(by = "1 day")
```
