### ISSUE TITLE
ts_scale sometimes returns tbl_ts with incorrect frequency

### ISSUE THREAD

**Issue by davidtedfordholt** [christophsax/tsbox#180]
Thank you for `tsbox`! I really appreciate the humility inherent in this sort of package.

When `ts_scale` is used on a tsibble object, it seems to convert the index variable to a date (if it is less frequent than daily), but does not convert it back to the original frequency after scaling. I assume this is due to the internal data structure not having an inherent frequency, but I haven't dug in. It's easy enough to convert, but might cause some issues for people new to tsibbles.

I'm happy to help, if I can and you would like.

```r
library(tsibble)
library(tsbox)

frequency(ts_scale(tourism)) == frequency(tourism)
```

**Comment by christophsax** [comment]
tsobx converts time indices to `Date` or `POSIXct`, so we loose the `yearquarter` class of the original tsibble. The resulting `Date` series seems fine to me, but `tsibble:::frequency.tbl_ts` guesses it as 7 for some reason:

``` r
library(tsbox)
library(tsibble)
ts_tbl(tourism)
#> [time]: 'Quarter' [value]: 'Trips'
#> # A tibble: 24,320 x 5
#>    Region   State           Purpose  Quarter    Trips
#>    <chr>    <chr>           <chr>    <date>     <dbl>
#>  1 Adelaide South Australia Business 1998-01-01  135.
#>  2 Adelaide South Australia Business 1998-04-01  110.
#>  3 Adelaide South Australia Business 1998-07-01  166.
#>  4 Adelaide South Australia Business 1998-10-01  127.
#>  5 Adelaide South Australia Business 1999-01-01  137.
#> # … with 24,310 more rows
```

So I don't think tsbox is wrong here. If you use the frequency guess function from tsbox, the results are the same (note that tsbox guesses a frequency for each series, so it is relatively slow):

``` r
library(tsibble)
library(tsbox)

all.equal(ts_summary(ts_scale(tourism))$freq, ts_summary(tourism)$freq)
#> [time]: 'Quarter' [value]: 'Trips' 
#> [time]: 'Quarter' [value]: 'Trips' 
#> [time]: 'Quarter' [value]: 'Trips' 
#> [time]: 'Quarter' [value]: 'Trips'
#> [1] TRUE
```
