### ISSUE TITLE
duplicated series error message 

### ISSUE THREAD

**Issue by balthasars** [christophsax/tsbox#181]
Hey Christoph! 

``` r
library(tsbox)
library(magrittr)
series <- tibble::tribble(
   ~date, ~value,
   "2012-01-01", 1,
   "2012-01-01", 1,
   "2012-01-02", 2,
   "2012-01-03", 3
)

series %>% 
   ts_df()
#> [time]: 'date'
#> Error: duplicated series:
```

<sup>Created on 2020-03-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Two things:
First: Duplicates are not pasted in by the helper function (I guess `tsbox:::its_init()` is the culprit), in both developer and CRAN versions.

Second: I'd suggest changing the error message. Maybe something like _"Series [series_name] contains duplicates: [list of duplicates]. Please remove."_ would be more informative than "duplicated series" (though also more verbose).  

Thanks for the package and I hope you're doing well!

**Comment by christophsax** [comment]
Hi there! Thanks.

I think it is fine that it does not take the object but the error message could be improved for the single series case. With multiple series, we would see the ids that cause the trouble; here, we have no ids but a single series with duplicated entries.

**Comment by christophsax** [comment]
Better now:

``` r
library(tsbox)
library(magrittr)
series <- tibble::tribble(
   ~date, ~value,
   "2012-01-01", 1,
   "2012-01-01", 1,
   "2012-01-02", 2,
   "2012-01-03", 3
)

series %>% 
   ts_df()
#> [time]: 'date'
#> Error: Series contains duplicated timestamps: 2012-01-01
```

<sup>Created on 2021-07-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by ncdingari** [comment]
This is closed without being fixed. I am getting similar error message.

**Comment by christophsax** [comment]
Are you using the dev version? There should be an error, but it should point you to the problem (duplicated values in time column).
