### ISSUE TITLE
ts_chain over several series

### ISSUE THREAD

**Issue by vincentpochon** [christophsax/tsbox#187]
Hi,

Let's say I have two dataframes  "gdp" and "fcst" containing respectively the gdp (in levels) and the forecasts (index) for a list of countries. How can I use ts_chain efficiently over all elements of the two dataframes since ts_chain is restricted to a single series?  

Thank you so much for your help.

Here you have a subset as an example:
`structure(list(id = c("ea", "ea", "ea", "ea", "usa", "usa", "usa", 
"usa"), time = structure(c(17897, 17987, 18078, 18170, 17897, 
17987, 18078, 18170), class = "Date"), value = c(18269.438796705, 
18290.189268628, 18351.812808526, 18368.378478867, 19820.078358555, 
19919.118637561, 20023.052341364, 20128.667799975)), row.names = c(NA, 
-8L), class = c("tbl_df", "tbl", "data.frame"))`
`structure(list(id = c("ea", "ea", "ea", "ea", "ea", "ea", "ea", 
"ea", "ea", "ea", "ea", "ea", "usa", "usa", "usa", "usa", "usa", 
"usa", "usa", "usa", "usa", "usa", "usa", "usa"), time = structure(c(17897, 
17987, 18078, 18170, 18262, 18353, 18444, 18536, 18628, 18718, 
18809, 18901, 17897, 17987, 18078, 18170, 18262, 18353, 18444, 
18536, 18628, 18718, 18809, 18901), class = "Date"), value = c(1.45151449601044, 
1.45365519771915, 1.45814823998987, 1.4598121967618, 1.40579372578542, 
1.22681364888771, 1.3392161722067, 1.37150961460015, 1.38502365641862, 
1.39867085758526, 1.41245253017324, 1.42636999918416, 2.76810101612519, 
2.78193312576644, 2.79644865824327, 2.81119906704644, 2.76065627806688, 
2.40397140976475, 2.61025537300438, 2.6792531074797, 2.70695273522584, 
2.7362501444335, 2.76652672628495, 2.79713831822693)), row.names = c(NA, 
-24L), class = c("tbl_df", "tbl", "data.frame"))`

**Comment by christophsax** [comment]
I guess it would make sense to for `ts_chain()` to be applicable over multiple series. We just need to make sure the two (or more than two) objects contain the same series.

For now, here is a hack:

``` r
dta0 <- structure(list(id = c("ea", "ea", "ea", "ea", "usa", "usa", "usa", "usa"), time = structure(c(17897, 17987, 18078, 18170, 17897, 17987, 18078, 18170), class = "Date"), value = c(18269.438796705, 18290.189268628, 18351.812808526, 18368.378478867, 19820.078358555, 19919.118637561, 20023.052341364, 20128.667799975)), row.names = c(NA, -8L), class = c("tbl_df", "tbl", "data.frame"))
dta1 <- structure(list(id = c("ea", "ea", "ea", "ea", "ea", "ea", "ea", "ea", "ea", "ea", "ea", "ea", "usa", "usa", "usa", "usa", "usa", "usa", "usa", "usa", "usa", "usa", "usa", "usa"), time = structure(c(17897, 17987, 18078, 18170, 18262, 18353, 18444, 18536, 18628, 18718, 18809, 18901, 17897, 17987, 18078, 18170, 18262, 18353, 18444, 18536, 18628, 18718, 18809, 18901), class = "Date"), value = c(1.45151449601044, 1.45365519771915, 1.45814823998987, 1.4598121967618, 1.40579372578542, 1.22681364888771, 1.3392161722067, 1.37150961460015, 1.38502365641862, 1.39867085758526, 1.41245253017324, 1.42636999918416, 2.76810101612519, 2.78193312576644, 2.79644865824327, 2.81119906704644, 2.76065627806688, 2.40397140976475, 2.61025537300438, 2.6792531074797, 2.70695273522584, 2.7362501444335, 2.76652672628495, 2.79713831822693)), row.names = c(NA, -24L), class = c("tbl_df", "tbl", "data.frame"))

library(tsbox)

chain_id <- function(id) {
  ts_chain(
    ts_pick(dta0, id),
    ts_pick(dta1, id)
  )
}

ids <- unique(dta0$id)

ans <- dplyr::bind_rows(lapply(ids, chain_id))

ts_plot(ans)
```

![](https://i.imgur.com/21OWf2z.png)

<sup>Created on 2020-05-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by vincentpochon** [comment]
Thank you very much for the workaround. Looking forward to the implementation of ts_chain() on multiple time series.
