### ISSUE TITLE
ts_index: average as base

### ISSUE THREAD

**Issue by vincentpochon** [christophsax/tsbox#188]
Hi Christoph
Is there a way to set an average as base in the ts_index function?
For example `ts_index(base = 2011)` is identical to `ts_index(base = "2011-01-01")`. 
How can I specify a range (here: average over 2011) so that is becomes something like `
ts_index(base = mean("2011-01-01", "2011-04-01", "2011-07-01", "2011-10-01"
))`?
 Thank you very much for your help.

**Comment by christophsax** [comment]
It is currently not possible, but I see that it may be a useful feature.

**Comment by christophsax** [comment]
For single series, it is easy enough:

``` r
library(tsbox)
ts_plot(
  `Jan 72 = 100` = ts_index(mdeaths, base = 1974),
  `Avg. 72 = 100` = mdeaths / ts_frequency(mdeaths, "year")[1]
)
```

![](https://i.imgur.com/BP3mb9J.png)

<sup>Created on 2021-07-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Still not too clear how the interface should look like. Perhaps with a from / to range like this?

```r
ts_index(mdeaths, base = c("1974-01-01", "1974-12-31"))
```

One probably always wants to use the average here, not the sum.

**Comment by christophsax** [comment]
... which works now:

``` r
library(tsbox)
ts_index(mdeaths, base = c("1974-01-01", "1974-12-31"))
#>            Jan       Feb       Mar       Apr       May       Jun       Jul
#> 1974 1.3427717 1.1722511 1.1810602 1.1810602 0.9388076 0.7859053 0.8054114
#> 1975 1.3232657 1.3446594 1.3547271 1.1533742 0.8828064 0.8104452 0.7462640
#> 1976 1.2710398 1.7303760 1.4365267 0.9306277 0.7481516 0.7299040 0.7003303
#> 1977 1.4094699 1.0281579 1.0835300 1.1332389 0.7840176 0.7311625 0.6839704
#> 1978 1.2704106 1.4371559 1.2219600 0.8953909 0.8431650 0.7468932 0.6908919
#> 1979 1.4239421 1.1451943 1.1615542 0.9633475 0.7645116 0.6764197 0.6644644
#>            Aug       Sep       Oct       Nov       Dec
#> 1974 0.7116564 0.7607362 0.9388076 1.0199780 1.1615542
#> 1975 0.7129149 0.6625767 0.8475696 0.9721567 1.2999843
#> 1976 0.6103508 0.6285984 0.7601070 0.9230769 1.2955797
#> 1977 0.6374076 0.6034293 0.7418594 0.7733207 1.0413717
#> 1978 0.6317445 0.6103508 0.7173195 0.6984427 1.1401605
#> 1979 0.6134969 0.5914740 0.6801951 0.8142205 0.8437942
```

<sup>Created on 2021-07-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
