### ISSUE TITLE
ts_index, can the time series be indexed to 0 instead of 1

### ISSUE THREAD

**Issue by nandyal** [christophsax/tsbox#190]
Hi Christoph,

I am trying to index a time-series data to start from 0 instead of 1.

 For eg. stock price (attached chart for Akamai Technologies listed in the US) on 01-01-2020 is indexed to1 (or 100%) and the stock has positive returns above 100% and negative below 100%. However if it's indexed to 0, it would be more intuitive.   

![image](https://user-images.githubusercontent.com/33078311/87924957-82a51f80-ca77-11ea-86dc-d9dcfb6e785d.png)

Thanks,
Venkat

**Comment by christophsax** [comment]
What I you just subtract 1 from it? (You could use `%ts-%` to make it work with all tsboxable objects). I still think it makes sense to have 1 or 100% as the base value.

``` r
library(tsbox)
ts_plot(ts_index(mdeaths) %ts-% 1)
```

![](https://i.imgur.com/V7nzyfo.png)

<sup>Created on 2021-07-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
