### ISSUE TITLE
Error in ts_to_date_time(x) caused by insufficient numerical precision

### ISSUE THREAD

**Issue by andrbachm** [christophsax/tsbox#195]
The following time series cannot be converted to a tibble (`ts_tbl(x)`) because, according to `ts_to_date_time()`, the time series starts in year 2019, even if it actually starts in January 2020. The problem is caused by insufficient numerical precision of the time series properties: `tsp(x)[1]` is equal to 2020, but `as.integer(tsp(x)[1])` turns out to be 2019, i.e. the starting period is probably equal to 2019.999999999999999...  

The problem can be solved by adding a small number to `tsp(x)[1]`, i.e. `tsp(x)[1]<-tsp(x)[1]+1e-10`

It would be great if `ts_to_date_time()` could deal with these numerical precision issues itself. 

```r

x <- structure(c(630281.753081821, 235227.873107744, 154707.066817058, 
100305.85207233, 85342.5246357035, 60098.2597624188, 82343.469973211, 
47554.7852940711, 59913.0224216896, 75176.8597796195, 113527.993702201, 
134633.594193566, 628278.343483888, 232719.876496459, 152284.06624942, 
97907.1055769522, 82940.4841807465, 57695.069727088, 79940.4032908286, 
45151.7724262788, 57510.0051554636, 72773.840022443, 111124.974090121, 
132230.574695585, 625875.323981777, 230316.856989173, 149881.046742212, 
95504.0860699763, 80537.4646737719, 55292.0502201031, 77537.3837838434, 
42748.7529192941, 55106.9856484789, 70370.8205154583, 108721.954583137, 
129827.555188601), .Tsp = c(2020, 2022.91666666667, 12), class = "ts")
```

Thanks a lot!

**Comment by christophsax** [comment]
Added a bit of extra tolerance, so the following will work as expected:

(The example above seems to be fine anyway, since `as.integer(tsp(x)[1])` is 2020 already)

``` r
library(tsbox)
x <- ts(c(1, 2, 3), start = 2019.999999999, frequency = 12)
as.integer(tsp(x)[1])
#> [1] 2019
ts_tbl(x)
#> # A tibble: 3 × 2
#>   time       value
#>   <date>     <dbl>
#> 1 2020-01-01     1
#> 2 2020-02-01     2
#> 3 2020-03-01     3
```

<sup>Created on 2021-07-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
