### ISSUE TITLE
oops

### ISSUE THREAD

**Issue by DonPipo85** [christophsax/tsbox#21]
> ts_align(m_textil_sa, imp_tn_63)
Error: 'NANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANA20857057.666666722707007.666666720621428.333333323348596.666666724574265.333333327381129.33333332248818026082161.333333328254738.666666727641047.333333323119595.33333332681091626144041.66666673018128326204054.666666728821851280828862940674925730131.6666667282278652707227130172315.666666726127424.666666728898095.6666667282872913135479626280716.333333329989416.666666729674301.666666731910291277321702896594031106558.333333332752420.333333326563837.666666729624944.666666729992645.333333336109226.666666731427685.333333334814979.666666734363424.66666673957557133917343.333333338348189.666666736124125399474423611488540022035.666666741026186.66666674290909035805701397617284208249945638247.333333336471957.333333338144496.66666674086459743655319.66666673542161238673961381228754236803238614590.333333341958512.666666741862190.666666746167908.666666738443086.333333342328764.666666739798414.666666748442620.666666741491321.333333
In addition: Warning message:
In if (!with %in% ts_varnames(x)) { :
  the condition has length > 1 and only the first element will be used
>

**Comment by christophsax** [comment]
not reproducible, and much has changed since
