### ISSUE TITLE
lists of time series

### ISSUE THREAD

**Issue by mbannert** [christophsax/tsbox#23]
despite all the fondness for `data.frame` like representation of time series with a dedicated date column, I think storing time series as lists as a few convenient advantages over storing them as a long format data.frame. E.g., 

my_list$some_series

references with to particular series and benefits from nice auto complete in larger lists. In a long format data.frame, singling out a single series is not possible as easily. Their might be other opinions (especially in the hadleyverse) on what's convenient, but since tsbox is a package of options... I'd suggest to add a function to got from lists to long formats and back even for single series (lists of 1). 

What do you think?

**Comment by christophsax** [comment]
Yes, I am sold. We should have:

`ts_tslist()`

which transforms every tsboxable object into a list with single `ts` objects. These lists will also be a tsboxable object and can be used with all functions from tsbox.

**Comment by christophsax** [comment]
Basic support now in latest. Keeping this undocumented and 'experimental' until we know what to do with it. But this should work now with swissdata input.

``` r
library(tsbox)
stopifnot(packageVersion("tsbox") >= "0.0.10.0")

ts_tslist(ts_c(mdeaths, AirPassengers))
#> $AirPassengers
#>      Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
#> 1949 112 118 132 129 121 135 148 148 136 119 104 118
#> 1950 115 126 141 135 125 149 170 170 158 133 114 140
#> 1951 145 150 178 163 172 178 199 199 184 162 146 166
#> 1952 171 180 193 181 183 218 230 242 209 191 172 194
#> 1953 196 196 236 235 229 243 264 272 237 211 180 201
#> 1954 204 188 235 227 234 264 302 293 259 229 203 229
#> 1955 242 233 267 269 270 315 364 347 312 274 237 278
#> 1956 284 277 317 313 318 374 413 405 355 306 271 306
#> 1957 315 301 356 348 355 422 465 467 404 347 305 336
#> 1958 340 318 362 348 363 435 491 505 404 359 310 337
#> 1959 360 342 406 396 420 472 548 559 463 407 362 405
#> 1960 417 391 419 461 472 535 622 606 508 461 390 432
#> 
#> $mdeaths
#>       Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
#> 1974 2134 1863 1877 1877 1492 1249 1280 1131 1209 1492 1621 1846
#> 1975 2103 2137 2153 1833 1403 1288 1186 1133 1053 1347 1545 2066
#> 1976 2020 2750 2283 1479 1189 1160 1113  970  999 1208 1467 2059
#> 1977 2240 1634 1722 1801 1246 1162 1087 1013  959 1179 1229 1655
#> 1978 2019 2284 1942 1423 1340 1187 1098 1004  970 1140 1110 1812
#> 1979 2263 1820 1846 1531 1215 1075 1056  975  940 1081 1294 1341
#> 
#> attr(,"class")
#> [1] "tslist" "list"

ts_plot(ts_tslist(ts_c(mdeaths, AirPassengers)))
```

![](https://i.imgur.com/dTnP0vk.png)



To make a function that work with`tslist` input workable with all tsboxable input, just do something like this at the beginning:
```
x <- ts_tslist(ts_c(...))
```

**Comment by christophsax** [comment]
@mbannert Just figured out that `attach` can be used with lists, so this seems neat, too:

``` r
library(tsbox)
dta <- ts_tslist(EuStockMarkets)

attach(dta)
head(DAX)
#> [1] 1628.75 1613.63 1606.51 1621.04 1618.16 1610.61

detach(dta)
head(DAX)
#> Error in head(DAX): object 'DAX' not found
```

**Comment by mbannert** [comment]
Cool, just another reason to like tslists as a supplement to long format data.tables.

**Comment by christophsax** [comment]
Or with `with` 😄 
``` r
library(tsbox)
with(ts_tslist(EuStockMarkets), head(DAX))
#> [1] 1628.75 1613.63 1606.51 1621.04 1618.16 1610.61
with(ts_tslist(EuStockMarkets), head(ts_df(DAX)))
#>                  time   value
#> 1 1991-07-01 03:18:27 1628.75
#> 2 1991-07-02 13:01:32 1613.63
#> 3 1991-07-03 22:44:37 1606.51
#> 4 1991-07-05 08:27:42 1621.04
#> 5 1991-07-06 18:10:48 1618.16
#> 6 1991-07-08 03:53:53 1610.61
```

**Comment by mbannert** [comment]
wow this is incredibly cool. I am a bit ashamed that I as big advocate time series lists and time series environments did not know about this. Thanks!
