### ISSUE TITLE
Adding function `ts_tbl_time`

### ISSUE THREAD

**Issue by Leo-Lee15** [christophsax/tsbox#90]
Thanks for creating such an awesome package! 

`tsbox` can convert time series stored as ts, xts, data.frame, data.table, tibble, zoo, tsibble or timeSeries to each other. And there is a tidyverse-like package [`tibbletime`](https://github.com/business-science/tibbletime) which is used in the `tidyquant` ecosystem. It would be a pity if the `tsbox` package does not support the `tibbletime` package.

So would you consider adding `ts_tbl_time()` function to this package?

**Comment by christophsax** [comment]
Sure, I can do that. I had it on the radar but finally wanted to get out a version. Next release...

**Comment by Leo-Lee15** [comment]
Thanks for the nice work!

**Comment by christophsax** [comment]
@Leo-Lee15 you can try out the dev version, will take a bit until on CRAN.

**Comment by christophsax** [comment]
implemented
